### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kayode-adechinan** [dmolony/dm3270#17]
Hello everyone, I have to use the dm3270 repo into some of our products at work. I am new in everything related to IBM and emulator. Could you please provide a basic documentation to the project or some resources where to look at for further understanding. Thanks.

**Comment by dmolony** [comment]
Hi

This is just a hobby project which I wrote for myself, and I do not support. I did not make you use it. I suggest you ask the people who decided to make an unsupported product mandatory for you to use.

**Comment by kayode-adechinan** [comment]
Thank you for your feedback. Your project looks very interesting. What will
it cost for you to support this project? For now, we just need  some sort
of documentation. Later on, if we need more assistance, we will discuss it
again.
Kind regards.

**Comment by vmdave9** [comment]
Hi, Kayode.
A good place to start if you are unfamiliar with the IBM mainframeand 3270s
is here:
https://en.wikipedia.org/wiki/IBM_3270#IBM_3472G
Other good links are these:
Steve Millington's TN3270 Protocol Cheat Sheet  http://ruelgnoj.co.uk/3270/
IBM 3270 Data Stream Programmer's Reference (GA23-0059-4)
https://bitsavers.computerhistory.org/pdf/ibm/3270/GA23-0059-4_3270_Data_Stream_Programmers_Reference_Dec88.pdf
Greg Price's 3270 Programming Overview
http://www.prycroft6.com.au/misc/3270.html
Tommy Sprinkles' 3270 Data Stream Programming
https://www.tommysprinkle.com/mvs/P3270/start.htm
Good luck.
DJ

**Comment by kayode-adechinan** [comment]
Thank you! I will check them out. I appreciate it.
Kind regards.
