### ISSUE TITLE
Change from GPL to Apache compatible license

### ISSUE THREAD

**Issue by rabelenda** [dmolony/dm3270#6]
Hello, I work in a team developing plugins for [Jmeter](https://jmeter.apache.org/), and in particular we are now interested on developing a plugin to access IBM servers through the IBM 3270 protocol to allow the general community to run load/performance tests on such systems with an open source and free tool.

We have found this great project and would like to use it as a dependency to implement the aforementioned plugin, but since this project uses GPL 3.0 license and [such license is not compatible with Jmeter one](https://www.apache.org/licenses/GPL-compatibility.html) we can't use it.

Is there any chance to change this project license to [one compatible with Apache license](https://www.apache.org/legal/resolved.html)? We would really appreciate it and we think it would be an even greater (than already is) contribution to the community. Obviously, we would keep a reference to your project and to you, for proper credits.

If you have any questions about the Jmeter plugin project or anything please let me know.

Regards.

**Comment by dmolony** [comment]
Changed.

**Comment by dmolony** [comment]
Hi

I have changed the license to Apache 2.0.

Cheers

Denis

**Comment by rabelenda** [comment]
Awesome!, thank you very much!, I will let you know when we release the jmeter plugin :)
